### ISSUE TITLE
好像意思说不能直接修改属性

### ISSUE THREAD

**Issue by qiaolin-pan** [dai-siki/vue-datepicker-simple#1]
报一下错误，我用的是vue2.0.3：
Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value"

非常好的插件，希望可以兼容vue2.0 :)

**Comment by dai-siki** [comment]
目前是基于vue@1.0+版本。不过兼容2.0肯定要做，既然提出来了，那就今天吧
